on:
  push:
    branches:
      - main

name: Deploy Backend

jobs:
  backend-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST}}
          username: ${{ secrets.SSH_USERNAME}}
          password: ${{ secrets.SSH_PASSWORD}}
          port: ${{ secrets.SSH_PORT }}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd /var/www/vhosts/elvirainfotech.org/quotekite-backend.elvirainfotech.org
            git pull origin main
            git status
            npm install
            npm run build
            pm2 restart quotekite-backend
            pm2 save
